#!/bin/bash
# =============================================================================
# Verathos Validator Environment Setup
# =============================================================================
#
# One-command environment setup for Bittensor validators.  No GPU required.
# Installs Python dependencies and shows next steps.
#
# After setup completes, follow the printed next-steps to create a wallet,
# fund your EVM address, and start the validator.
#
# Usage:
#   bash scripts/setup_validator.sh              # Full install
#   bash scripts/setup_validator.sh --skip-install  # Skip install, just verify
#
# Environment variables:
#   WORKSPACE          - Persistent volume path (default: /workspace)
#   VERATHOS_REPO_URL  - Git clone URL (default: current directory if present)
#
# =============================================================================

set -e

# ── Parse arguments ──────────────────────────────────────────────────────────

SKIP_INSTALL=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --skip-install) SKIP_INSTALL=true; shift ;;
        *) echo "Unknown flag: $1"; exit 1 ;;
    esac
done

# ── Paths ────────────────────────────────────────────────────────────────────

WORKSPACE="${WORKSPACE:-/workspace}"
PYTHON="${PYTHON:-python3}"

echo ""
echo "============================================================"
echo "  Verathos Validator Environment Setup"
echo "============================================================"

# ── Clone or update repo ─────────────────────────────────────────────────────

if [ -f "pyproject.toml" ] && grep -q "verathos" pyproject.toml 2>/dev/null; then
    REPO_DIR="$(pwd)"
    echo "  Using current directory: $REPO_DIR"
elif [ -d "${WORKSPACE}/verathos" ]; then
    REPO_DIR="${WORKSPACE}/verathos"
    echo "  Updating existing repo at $REPO_DIR..."
    cd "$REPO_DIR" && git pull
else
    if [ -z "$VERATHOS_REPO_URL" ]; then
        echo "ERROR: Repo not found and VERATHOS_REPO_URL not set."
        echo "Either clone the repo manually or set VERATHOS_REPO_URL."
        exit 1
    fi
    REPO_DIR="${WORKSPACE}/verathos"
    echo "  Cloning repo to $REPO_DIR..."
    git clone "$VERATHOS_REPO_URL" "$REPO_DIR"
fi

cd "$REPO_DIR"

# ── Venv setup ───────────────────────────────────────────────────────────────

VENV_DIR="${REPO_DIR}/.venv-validator"

if [ ! -d "$VENV_DIR" ]; then
    echo ""
    echo "  Creating venv..."
    if ! $PYTHON -m venv "$VENV_DIR" 2>/dev/null; then
        echo "  python3-venv not installed — installing..."
        PY_VER=$($PYTHON -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
        if command -v apt-get &>/dev/null; then
            sudo apt-get update -qq && sudo apt-get install -y -qq "python${PY_VER}-venv" 2>&1 | tail -3
        elif command -v dnf &>/dev/null; then
            sudo dnf install -y "python${PY_VER}-venv" 2>&1 | tail -3
        else
            echo "  ERROR: Cannot install python3-venv automatically."
            echo "  Please install it manually: apt install python${PY_VER}-venv"
            exit 1
        fi
        $PYTHON -m venv "$VENV_DIR"
    fi
else
    echo "  Using existing venv: $VENV_DIR"
fi

# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"
PYTHON="$VENV_DIR/bin/python"

echo "  Python: $($PYTHON --version 2>&1) ($PYTHON)"

# ── Install dependencies ─────────────────────────────────────────────────────

if [ "$SKIP_INSTALL" = false ]; then
    echo ""
    echo "Installing Python dependencies..."
    $PYTHON -m pip install --no-cache-dir -e ".[neurons]" 2>&1 | tail -20

    # Pin async-substrate-interface <2: ASI 2.0 breaks bittensor 10.x
    # (removes ScaleObj) and introduces scalecodec/cyscale namespace conflict.
    # Force downgrade if 2.x was pulled transitively.
    $PYTHON -m pip install --no-cache-dir 'async-substrate-interface>=1.6,<2' 2>&1 | tail -3

    # Install zkllm wheel (required for verallm imports even without GPU)
    PY_VER=$($PYTHON -c "import sys; print(f'cp{sys.version_info.major}{sys.version_info.minor}')")
    ZKLLM_WHEEL=$(ls "${REPO_DIR}/dist"/zkllm-*-${PY_VER}-*.whl 2>/dev/null | head -1)
    if [ -n "$ZKLLM_WHEEL" ]; then
        echo "  Installing zkllm wheel..."
        $PYTHON -m pip install --no-cache-dir "$ZKLLM_WHEEL" 2>&1 | tail -5
    else
        echo "  WARNING: No zkllm wheel found for $PY_VER in dist/"
    fi

    echo ""
    echo "Installation complete."
else
    echo "  Skipping install (--skip-install)"
fi

# ── Persist environment for future SSH sessions ──────────────────────────────

ENV_FILE="${REPO_DIR}/.env-validator.sh"
cat > "$ENV_FILE" <<ENVEOF
# Auto-generated by setup_validator.sh
if [ -f "${VENV_DIR}/bin/activate" ]; then
    source "${VENV_DIR}/bin/activate"
fi
ENVEOF

BASHRC="${HOME}/.bashrc"
if ! grep -qF "verathos/.env-validator.sh" "$BASHRC" 2>/dev/null; then
    echo "" >> "$BASHRC"
    echo "# Verathos validator environment (auto-added by setup_validator.sh)" >> "$BASHRC"
    echo "[ -f \"${ENV_FILE}\" ] && source \"${ENV_FILE}\"" >> "$BASHRC"
    echo "  Persisted env to $ENV_FILE (sourced from .bashrc)"
else
    echo "  Env already persisted in .bashrc"
fi

# ── Next steps ───────────────────────────────────────────────────────────────

echo ""
echo "============================================================"
echo "  Validator environment ready!"
echo "============================================================"
echo ""
echo "  Next steps:"
echo ""
echo "  0. Activate the environment:"
echo "     cd $(pwd)"
echo "     source .venv-validator/bin/activate"
echo ""
echo "  1. Set up wallet (create locally, then copy to this server):"
echo "     btcli wallet create --wallet.name validator"
echo "     btcli subnet register --wallet.name validator --netuid 96 --subtensor.network finney"
echo ""
echo "     Copy to this server (coldkeypub + hotkey only — never the coldkey):"
echo "     btcli wallet regen-coldkeypub --wallet.name validator --ss58-address <SS58>"
echo "     btcli wallet regen-hotkey --wallet.name validator --hotkey default"
echo ""
echo "  2. Fund your EVM address (optional, for on-chain reportOffline votes):"
echo "     python scripts/show_evm_info.py --wallet validator --hotkey default"
echo "     btcli wallet transfer --dest <SS58_MIRROR> --amount 0.05 --subtensor.network finney"
echo ""
echo "     Skip with --no-evm if you don't want to fund."
echo ""
echo "  3. Run the setup wizard to configure subtensor, analytics, and PM2:"
echo "     verathos setup validator"
echo ""
echo "  See docs/setup.md for full details."
echo "============================================================"
